const B=[
['assert','v. 断言；声称；坚持认为','The author asserts that the current system needs reform.','作者断言现行制度需要改革。','as- 加强 + sert“连接/放置” → 断言'],['paradox','n. 悖论；看似矛盾的现象','Technology can create a paradox.','科技可能造成悖论。','para- 反常 + dox 观点'],['hostility','n. 敌意；敌对；反对','The proposal was met with hostility.','这项提议遭到反对。','hostile + -ity'],['alleviation','n. 缓解；减轻','The policy aims at the alleviation of poverty.','政策旨在缓解贫困。','alleviate + -ion'],['poverty','n. 贫困；贫穷','Education can help families escape poverty.','教育能帮助家庭摆脱贫困。','poor 相关词源 + -ty'],['debate','n./v. 争论；辩论；讨论','Scientists continue to debate the issue.','科学家继续讨论这个问题。','de- + bat“打” → 言语交锋'],['tribe','n. 部落；族群','The tribe preserved its language.','这个部落保留了自己的语言。',''],['dwelling','n. 住所；住宅','The old dwelling became a museum.','旧住宅变成了博物馆。','dwell + -ing'],['livestock','n. 牲畜；家畜','Farmers raise livestock.','农民饲养牲畜。','live + stock'],['havoc','n. 大破坏；严重混乱','The storm caused havoc.','暴风雨造成严重破坏。',''],['emancipate','v. 解放；使摆脱束缚','Education can emancipate people from ignorance.','教育能使人摆脱无知。','e-/ex- 出 + mancip 控制 + -ate'],['sphere','n. 领域；范围；球体','Technology affects every sphere of life.','科技影响生活各领域。','spher 球'],['apt','adj. 恰当的；易于……的；有……倾向的','Children are apt to imitate adults.','孩子往往会模仿成年人。',''],['misconception','n. 误解；错误观念','This is a common misconception.','这是一种常见误解。','mis- 错误 + concept + -ion'],['refer','v. 提到；谈及；参考','The report refers to recent studies.','报告提到了近期研究。','re- + fer 带/拿'],['weave','v. 编织；交织；使融入','The writer weaves facts into the story.','作者把事实融入故事。',''],['enduring','adj. 持久的；长期存在的','The research had an enduring influence.','研究产生了持久影响。','endure + -ing'],['presume','v. 假定；推定；想当然地认为','We should not presume that price means quality.','我们不应想当然认为价格代表质量。','pre- 在前 + sume 取'],['misinterpretation','n. 误解；错误解释','A misinterpretation led to the wrong conclusion.','错误解读导致错误结论。','mis- + interpret + -ation'],['irresistible','adj. 无法抗拒的；极具吸引力的','The offer seemed irresistible.','这个提议似乎难以抗拒。','ir- 不 + resist + -ible'],['enormous','adj. 巨大的；庞大的','The project requires enormous resources.','项目需要大量资源。','e-/ex- 超出 + norm 标准 + -ous'],['grain of salt','phr. 怀疑态度；保留态度','Take online rumors with a grain of salt.','对网络传言应持保留态度。',''],['hypothesis','n. 假设；假说','Researchers tested the hypothesis.','研究人员检验了假设。','hypo- + thesis 论题'],['appraisal','n. 评价；评估；鉴定','The report provides an appraisal of the risks.','报告对风险进行了评估。','appraise + -al'],['embed','v. 使嵌入；使深植','These values are embedded in the culture.','这些价值观深植于文化中。','em-/en- 进入 + bed'],['desolation','n. 荒凉；荒芜；孤寂','The village was a scene of desolation.','村庄一片荒凉。','desolate + -ion'],['ordinary','adj. 普通的；平常的；一般的','Ordinary people can make a difference.','普通人也能带来改变。','ordin + -ary'],['interval','n. 间隔；间歇','There was a short interval between lectures.','两场讲座间有短暂间隔。','inter- 之间'],['symmetry','n. 对称；匀称','The design has perfect symmetry.','设计具有完美对称性。','sym-/syn- 相同 + metr 测量'],['enthusiastic','adj. 热情的；热心的','Students were enthusiastic about the course.','学生对课程很热情。','enthusiasm + -astic'],['endorse','v. 支持；赞同；认可','Experts endorse the proposal.','专家支持该提议。','en- + dors 背'],['horizon','n. 地平线；眼界；范围','Travel can broaden your horizons.','旅行能开阔眼界。',''],['intermittent','adj. 间歇的；断断续续的','Intermittent rain continued all afternoon.','整个下午断断续续下雨。','inter- + mit + -ent'],['scatter','v. 分散；散布；散射','The wind scattered the leaves.','风吹散了树叶。',''],['status','n. 地位；身份；状况；状态','Education can influence social status.','教育可能影响社会地位。','stat 状态 + -us'],['scale','n. 规模；范围；等级','The problem exists on a global scale.','问题存在于全球范围。',''],['acclaim','n./v. 称赞；赞誉','The novel received widespread acclaim.','小说获得广泛赞誉。','ac- + claim 呼喊'],['tranquil','adj. 宁静的；平静的','The lake was tranquil in the morning.','清晨湖面很宁静。',''],['excessive','adj. 过度的；过多的','Excessive phone use may affect sleep.','过度使用手机可能影响睡眠。','excess + -ive'],['affluent','adj. 富裕的；富足的','The service targets affluent consumers.','服务面向富裕消费者。','af- + flu 流 + -ent'],['irresponsible','adj. 不负责任的','It is irresponsible to ignore the risks.','忽视风险是不负责任的。','ir- 不 + responsible'],['hollowed-out','adj. 被掏空的；衰败的','Population loss left the town hollowed-out.','人口流失使小镇衰败。','hollow + out'],['conservatism','n. 保守主义；保守倾向','Uncertainty may encourage conservatism in spending.','不确定性可能使消费更保守。','conserve + -ism'],['radiance','n. 光辉；光彩；容光焕发','The sun filled the room with radiance.','阳光使房间充满光辉。','radi 光线 + -ance'],['scarce','adj. 缺乏的；稀少的；不足的','Clean water is scarce in some regions.','一些地区清洁水稀缺。',''],['align','v. 使对齐；使一致','The policy should align with long-term goals.','政策应与长期目标一致。','a-/ad- 向 + line'],['inevitable','adj. 不可避免的；必然发生的','Some uncertainty is inevitable.','一定程度的不确定性不可避免。','in- 不 + evit 避免 + -able'],['resemblance','n. 相似；相像','There is a resemblance between the theories.','两种理论存在相似之处。','resemble + -ance'],['warrant','v. 证明……合理；使有必要','The evidence does not warrant that conclusion.','证据不足以支持该结论。',''],['deplorable','adj. 糟糕的；令人遗憾的；应受谴责的','Workers lived in deplorable conditions.','工人生活条件很糟糕。','deplore + -able'],['detached','adj. 分离的；独立的；冷静客观的','Researchers should remain detached.','研究人员应保持客观。','de- 离开 + attach + -ed'],['eclipse','n. 日食；月食；v. 使黯然失色；超过','Her latest achievement eclipsed earlier successes.','她的新成就使以往成功黯然失色。','ec-/ex- 离开'],['evaluate','v. 评估；评价；估计','Students should evaluate information critically.','学生应批判性评估信息。','valu 价值 + -ate'],['extreme','adj. 极端的；极度的','The region experienced extreme weather.','该地区经历了极端天气。','extr 最外 + -eme'],['tribal','adj. 部落的；部族的','The custom remains important in tribal communities.','该习俗在部落社区仍很重要。','tribe + -al'],['populist','n. 民粹主义者；adj. 民粹主义的','The politician adopted populist language.','该政治人物采用了民粹主义式言辞。','popul 人民 + -ist'],['innovative','adj. 创新的；革新的','The school introduced an innovative teaching model.','学校引入了一种创新的教学模式。','innovate 创新 + -ive 形容词后缀'],['enrollment','n. 注册；入学；入学人数','Student enrollment has declined in recent years.','近年来学生入学人数有所下降。','enroll 登记/注册 + -ment 名词后缀'],['pilot','v. 试行；试点；n. 飞行员','The school piloted the new program before expanding it.','学校在扩大该项目之前先进行了试点。',''],['hammer out','phr. 反复商讨后制定；达成','The teachers met to hammer out a plan for every student.','教师们开会反复商讨，为每位学生制定方案。','固定短语'],['gamble','n./v. 冒险；赌博','Changing the teaching model was a gamble that might pay off.','改变教学模式是一场可能取得回报的冒险。',''],['isolation','n. 隔离；孤立；独处','Teachers often struggle when they work in isolation.','教师独自工作时往往会面临困难。','isolate 隔离 + -ion 名词后缀'],['overhaul','v./n. 全面改革；彻底检修','The school decided to overhaul its teaching approach.','学校决定全面改革其教学方式。','over- 彻底 + haul 拉/拖；引申为彻底检查改革'],['frustration','n. 挫折；沮丧；令人沮丧的事','Lack of support can cause frustration among teachers.','缺乏支持会让教师产生挫败感。','frustrate 使沮丧 + -ion 名词后缀'],['bewilder','v. 使困惑；使不知所措','The difficult explanation bewildered many students.','这段困难的解释让许多学生感到困惑。','be- 加强 + wilder“使迷失方向” → 使困惑'],['thorny','adj. 棘手的；麻烦的','The reform raises several thorny questions.','这项改革带来了几个棘手的问题。','thorn 刺 + -y → 多刺的；引申为棘手的'],['recruit','v. 招募；招聘；n. 新成员','The school is trying to recruit more volunteer teachers.','学校正努力招募更多志愿教师。','re- 再/重新 + cruit“增长”相关词源'],['pay off','phr. 取得成功；得到回报；还清','Their efforts finally paid off.','他们的努力最终取得了回报。','固定短语'],['half','n. 一半；半个；半边','One half of the brain controls the opposite side of the body.','大脑的一侧控制身体相反的一侧。',''],['personality','n. 性格；个性；人格','Personality is not determined by one half of the brain.','性格并不是由大脑的某一半决定的。','person“人” + -ality 名词后缀'],['dogma','n. 教条；信条；（文中）法则','The teacher explained the central dogma of biology.','老师讲解了生物学的中心法则。',''],['cite','v. 引用；援引；举……为例','The author cites a teacher’s experience as evidence.','作者引用一位教师的经历作为证据。',''],['morale','n. 士气；精神状态','The new model may improve teacher morale.','这种新模式可能提高教师士气。',''],['retention','n. 保留；留任；保持','The school hopes to improve teacher retention.','学校希望提高教师留任率。','retain 保留 + -tion 名词后缀'],['collaborate','v. 合作；协作','Teachers have more opportunities to collaborate with colleagues.','教师有更多机会与同事合作。','col- 共同 + labor“劳动” + -ate → 共同工作'],
['staggering','adj. 惊人的；令人震惊的','The report revealed a staggering amount of wasted time.','报告显示被浪费的时间多得惊人。','stagger“使震惊/蹒跚” + -ing'],
['relief','n. 宽慰；缓解；减轻','Finishing the task brought a sense of relief.','完成任务让人感到如释重负。','re- 回 + lief“轻/乐”相关词源'],
['fatigue','n./v. 疲劳；疲惫；使疲劳','Long meetings can cause mental fatigue.','长时间会议会造成精神疲劳。','fatig“疲劳” + -ue'],
['investigation','n. 调查；研究','The issue deserves further investigation.','这个问题值得进一步研究。','investigate + -ion'],
['precise','adj. 精确的；准确的；明确的','The researchers gave a precise definition of the problem.','研究人员对这个问题给出了准确的定义。','pre- 前 + cis“切” → 切得精确'],
['hypothesise','v. 假设；提出假说','Scientists hypothesise that poor meetings drain mental energy.','科学家假设低效会议会消耗心理能量。','hypothesis + -ise'],
['drain','v. 消耗；耗尽；排出；n. 消耗','Unnecessary meetings drain employees\' energy.','不必要的会议会耗尽员工的精力。',''],
['vitality','n. 活力；生命力','Short breaks can help restore vitality.','短暂休息有助于恢复活力。','vital“有生命力的” + -ity'],
['conservation','n. 保存；保护；节约','Energy conservation becomes important when resources are low.','资源不足时，节省能量就变得重要。','conserve + -ation'],
['productivity','n. 生产率；生产力','Too many meetings may reduce productivity.','会议过多可能降低生产力。','productive + -ity'],
['transition','n./v. 过渡；转变；转换','It takes effort to transition from one task to another.','从一项任务切换到另一项任务需要付出精力。','trans- 横过 + it“走” + -ion'],
['cognitive','adj. 认知的；思维的','Task switching requires cognitive effort.','任务切换需要认知努力。','cognit“认识” + -ive'],
['detach','v. 使分离；脱离；摆脱','Workers need time to detach from the previous task.','员工需要时间从上一项任务中抽离出来。','de- 离开 + attach'],
['speculate','v. 推测；猜测；思索','Researchers speculate about the causes of meeting fatigue.','研究人员推测会议疲劳的成因。','spec“看” + -ulate'],
['combat','v./n. 对抗；防止；战斗','Managers can combat meeting fatigue by shortening meetings.','管理者可以通过缩短会议来对抗会议疲劳。','com- 共同 + bat“打”'],
['concise','adj. 简明的；简洁的','A concise agenda can make meetings more efficient.','简洁的议程可以提高会议效率。','con- 加强 + cis“切” → 切短'],
['remedy','n./v. 补救办法；纠正；治疗','Reducing unnecessary meetings is one possible remedy.','减少不必要的会议是一种可行的补救办法。','re- 再 + med“治疗”'],
['agenda','n. 议程；待办事项','Every meeting should have a clear agenda.','每次会议都应该有明确的议程。','ag“做” + -enda“应做之事”'],
['vent','v. 发泄；表达；排放','Employees sometimes use meetings to vent frustration.','员工有时会利用会议发泄挫败感。','vent“风/出口”'],
['scarcity','n. 缺乏；稀缺','Time scarcity forces teams to set priorities.','时间稀缺迫使团队确定优先事项。','scarce + -ity'],
['empirical','adj. 实证的；以观察或实验为依据的','The claim needs empirical evidence.','这一观点需要实证证据。','empir“经验” + -ical'],
['diminish','v. 减少；削弱；降低','Shorter meetings may diminish mental fatigue.','更短的会议可能减轻精神疲劳。','di-/de- 向下 + min“少”'],
['facilitator','n. 促进者；协调者；会议主持人','A skilled facilitator can keep a meeting focused.','熟练的协调者可以让会议保持重点。','facilitate + -or'],
['steward','n. 管理者；负责人；乘务员；v. 管理','Managers should act as stewards of employees\' time.','管理者应当负责任地管理员工的时间。',''],
['foresee','v. 预见；预知','Good managers foresee problems before they grow.','优秀的管理者会在问题扩大前预见它们。','fore- 在前 + see'],
['eliminate','v. 消除；排除；淘汰','The company eliminated several unnecessary meetings.','公司取消了几场不必要的会议。','e-/ex- 出 + limin“门槛/界限” + -ate'],
['dispensable','adj. 非必需的；可省去的','Some meetings are entirely dispensable.','有些会议完全可以省去。','dispense“免除/分配” + -able']
];
const IPA={
  "assert": "/əˈsɝːt/",
  "paradox": "/ˈperədɑːks/",
  "hostility": "/hɑːˈstɪləti/",
  "alleviation": "/əˌliːviˈeɪʃən/",
  "poverty": "/ˈpɑːvərti/",
  "debate": "/dɪˈbeɪt/",
  "tribe": "/traɪb/",
  "dwelling": "/ˈdwelɪŋ/",
  "livestock": "/ˈlaɪvstɑːk/",
  "havoc": "/ˈhævək/",
  "emancipate": "/ɪˈmænsəpeɪt/",
  "sphere": "/sfɪr/",
  "apt": "/æpt/",
  "misconception": "/ˌmɪskənˈsepʃən/",
  "refer": "/rɪˈfɝː/",
  "weave": "/wiːv/",
  "enduring": "/ɪnˈdʊrɪŋ/",
  "presume": "/prɪˈzuːm/",
  "misinterpretation": "/ˌmɪsɪnˌtɝːprəˈteɪʃən/",
  "irresistible": "/ˌɪrɪˈzɪstəbəl/",
  "enormous": "/ɪˈnɔːrməs/",
  "grain of salt": "/ɡreɪn əv sɔːlt/",
  "hypothesis": "/haɪˈpɑːθəsɪs/",
  "appraisal": "/əˈpreɪzəl/",
  "embed": "/ɪmˈbed/",
  "desolation": "/ˌdesəˈleɪʃən/",
  "ordinary": "/ˈɔːrdəneri/",
  "interval": "/ˈɪntərvəl/",
  "symmetry": "/ˈsɪmətri/",
  "enthusiastic": "/ɪnˌθuːziˈæstɪk/",
  "endorse": "/ɪnˈdɔːrs/",
  "horizon": "/həˈraɪzən/",
  "intermittent": "/ˌɪntərˈmɪtənt/",
  "scatter": "/ˈskætər/",
  "status": "/ˈsteɪtəs/",
  "scale": "/skeɪl/",
  "acclaim": "/əˈkleɪm/",
  "tranquil": "/ˈtræŋkwəl/",
  "excessive": "/ɪkˈsesɪv/",
  "affluent": "/ˈæfluənt/",
  "irresponsible": "/ˌɪrɪˈspɑːnsəbəl/",
  "hollowed-out": "/ˌhɑːloʊd ˈaʊt/",
  "conservatism": "/kənˈsɝːvətɪzəm/",
  "radiance": "/ˈreɪdiəns/",
  "scarce": "/skers/",
  "align": "/əˈlaɪn/",
  "inevitable": "/ɪnˈevɪtəbəl/",
  "resemblance": "/rɪˈzembləns/",
  "warrant": "/ˈwɔːrənt/",
  "deplorable": "/dɪˈplɔːrəbəl/",
  "detached": "/dɪˈtætʃt/",
  "eclipse": "/ɪˈklɪps/",
  "evaluate": "/ɪˈvæljueɪt/",
  "extreme": "/ɪkˈstriːm/",
  "tribal": "/ˈtraɪbəl/",
  "populist": "/ˈpɑːpjəlɪst/",
  "innovative": "/ˈɪnəveɪtɪv/",
  "enrollment": "/ɪnˈroʊlmənt/",
  "pilot": "/ˈpaɪlət/",
  "hammer out": "/ˈhæmər aʊt/",
  "gamble": "/ˈɡæmbəl/",
  "isolation": "/ˌaɪsəˈleɪʃən/",
  "overhaul": "/ˌoʊvərˈhɔːl/",
  "frustration": "/frʌˈstreɪʃən/",
  "bewilder": "/bɪˈwɪldər/",
  "thorny": "/ˈθɔːrni/",
  "recruit": "/rɪˈkruːt/",
  "pay off": "/peɪ ɔːf/",
  "half": "/hæf/",
  "personality": "/ˌpɝːsəˈnæləti/",
  "dogma": "/ˈdɔːɡmə/",
  "cite": "/saɪt/",
  "morale": "/məˈræl/",
  "retention": "/rɪˈtenʃən/",
  "collaborate": "/kəˈlæbəreɪt/",
  "staggering": "/ˈstæɡərɪŋ/",
  "relief": "/rɪˈliːf/",
  "fatigue": "/fəˈtiːɡ/",
  "investigation": "/ɪnˌvestɪˈɡeɪʃən/",
  "precise": "/prɪˈsaɪs/",
  "hypothesise": "/haɪˈpɒθəsaɪz/",
  "drain": "/dreɪn/",
  "vitality": "/vaɪˈtæləti/",
  "conservation": "/ˌkɑːnsərˈveɪʃən/",
  "productivity": "/ˌproʊdʌkˈtɪvəti/",
  "transition": "/trænˈzɪʃən/",
  "cognitive": "/ˈkɑːɡnətɪv/",
  "detach": "/dɪˈtætʃ/",
  "speculate": "/ˈspekjəleɪt/",
  "combat": "/ˈkɑːmbæt/",
  "concise": "/kənˈsaɪs/",
  "remedy": "/ˈremədi/",
  "agenda": "/əˈdʒendə/",
  "vent": "/vent/",
  "scarcity": "/ˈskersəti/",
  "empirical": "/ɪmˈpɪrɪkəl/",
  "diminish": "/dɪˈmɪnɪʃ/",
  "facilitator": "/fəˈsɪləteɪtər/",
  "steward": "/ˈstuːərd/",
  "foresee": "/fɔːrˈsiː/",
  "eliminate": "/ɪˈlɪməneɪt/",
  "dispensable": "/dɪˈspensəbəl/"
};
